name: todo_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_it: ^7.6.7
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  go_router: ^14.1.4
  dio: ^5.4.3+1
  flutter_styled_toast: ^2.2.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  intl: ^0.18.1
  path_provider: ^2.1.3
  flutter_secure_storage: ^9.2.2
  uuid: ^4.4.0
  golden_toolkit: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans_Regular.ttf
